// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvdnOpYi9b0KAkWisNoXYGjXurtdlXkK0',
    appId: '1:929746281541:web:db94f885d597db9028ef2c',
    messagingSenderId: '929746281541',
    projectId: 'kota-indah-75b91',
    authDomain: 'kota-indah-75b91.firebaseapp.com',
    storageBucket: 'kota-indah-75b91.firebasestorage.app',
    measurementId: 'G-HHS82N812D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXq_Cte221ZHLXb01YUHxjvXoG14zjiI0',
    appId: '1:929746281541:android:3e8952884ea10e1028ef2c',
    messagingSenderId: '929746281541',
    projectId: 'kota-indah-75b91',
    storageBucket: 'kota-indah-75b91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbw0-phhSrIphorAWl7CHMRq-a13QZdQs',
    appId: '1:929746281541:ios:ba6ae2126e30da2328ef2c',
    messagingSenderId: '929746281541',
    projectId: 'kota-indah-75b91',
    storageBucket: 'kota-indah-75b91.firebasestorage.app',
    iosClientId: '929746281541-bhfi90us3o7sf6vcn9u3md2lp79b46d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbw0-phhSrIphorAWl7CHMRq-a13QZdQs',
    appId: '1:929746281541:ios:ba6ae2126e30da2328ef2c',
    messagingSenderId: '929746281541',
    projectId: 'kota-indah-75b91',
    storageBucket: 'kota-indah-75b91.firebasestorage.app',
    iosClientId: '929746281541-bhfi90us3o7sf6vcn9u3md2lp79b46d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvdnOpYi9b0KAkWisNoXYGjXurtdlXkK0',
    appId: '1:929746281541:web:d89c4bf7e6319f8628ef2c',
    messagingSenderId: '929746281541',
    projectId: 'kota-indah-75b91',
    authDomain: 'kota-indah-75b91.firebaseapp.com',
    storageBucket: 'kota-indah-75b91.firebasestorage.app',
    measurementId: 'G-7R894EL8TH',
  );
}
